import {registerCustomVideoPlayer} from './js/custom-video.js';
import {registerAside} from './js/aside.js';
// import {registerMap} from './js/map';
import {registerModal} from './js/modal.js';
import {registerGallery} from './js/gallery.js';
import {registerExploreSlider} from './js/explore-slider.js';
import {registerWelcomeCarousel} from './js/welcome-carousel.js';
import {registerTicketsBase} from './js/tickets-base.js';
import {registerFormValidation} from './js/form-validation.js';
import {registerModalForm} from './js/modal-form.js';

registerCustomVideoPlayer();
registerAside();
// registerMap();
registerModal();
registerGallery();
registerExploreSlider();
registerWelcomeCarousel();
registerTicketsBase();
registerFormValidation();
registerModalForm();
